spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

server:
  port: 8080
