spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: POSTGRES

server:
  port: 8080
